// Regenerate src/data/meta.ts from the per-level content files so the Home
// overview counts can never drift from the actual data. Run automatically
// before dev/build (see package.json), or manually: `npm run gen:meta`.
//
// Counts are derived from each item's structured id (e.g. "kanji:N5:会"), which
// appears exactly once per item and never inside content strings — so this is
// robust to any reformatting of the data files.
import fs from 'node:fs'

const LEVELS = ['N5', 'N4', 'N3', 'N2', 'N1']
const DIMS = ['kanji', 'vocab', 'grammar']
const dataDir = new URL('../src/data/', import.meta.url)

function countsForLevel(level) {
  const file = new URL(`${level.toLowerCase()}.ts`, dataDir)
  let text = ''
  try {
    text = fs.readFileSync(file, 'utf8')
  } catch {
    return { kanji: 0, vocab: 0, grammar: 0 }
  }
  const out = {}
  for (const dim of DIMS) {
    // Count occurrences of the id-value prefix, e.g. "kanji:N5:
    out[dim] = text.split(`"${dim}:${level}:`).length - 1
  }
  return out
}

const counts = Object.fromEntries(LEVELS.map((l) => [l, countsForLevel(l)]))

const body = `import type { Dimension, JlptLevel } from '../types'

// AUTO-GENERATED by scripts/gen-meta.mjs — do not edit by hand.
// Lightweight per-level item counts so the Home dashboard can show totals and
// "new on deck" without loading the (large) content modules. Regenerated from
// src/data/<level>.ts on every dev/build, so it can't drift from the content.
export const LEVEL_COUNTS: Record<JlptLevel, Record<Dimension, number>> = ${JSON.stringify(counts, null, 2)}

export const POPULATED_LEVELS: JlptLevel[] = (Object.keys(LEVEL_COUNTS) as JlptLevel[]).filter(
  (l) => LEVEL_COUNTS[l].kanji + LEVEL_COUNTS[l].vocab + LEVEL_COUNTS[l].grammar > 0,
)
`

fs.writeFileSync(new URL('meta.ts', dataDir), body)
console.log('Wrote src/data/meta.ts:', JSON.stringify(counts))
