import type { Dimension, JlptLevel } from '../types'

// AUTO-GENERATED by scripts/gen-meta.mjs — do not edit by hand.
// Lightweight per-level item counts so the Home dashboard can show totals and
// "new on deck" without loading the (large) content modules. Regenerated from
// src/data/<level>.ts on every dev/build, so it can't drift from the content.
export const LEVEL_COUNTS: Record<JlptLevel, Record<Dimension, number>> = {
  "N5": {
    "kanji": 104,
    "vocab": 543,
    "grammar": 94
  },
  "N4": {
    "kanji": 201,
    "vocab": 631,
    "grammar": 181
  },
  "N3": {
    "kanji": 332,
    "vocab": 837,
    "grammar": 166
  },
  "N2": {
    "kanji": 0,
    "vocab": 0,
    "grammar": 0
  },
  "N1": {
    "kanji": 0,
    "vocab": 0,
    "grammar": 0
  }
}

export const POPULATED_LEVELS: JlptLevel[] = (Object.keys(LEVEL_COUNTS) as JlptLevel[]).filter(
  (l) => LEVEL_COUNTS[l].kanji + LEVEL_COUNTS[l].vocab + LEVEL_COUNTS[l].grammar > 0,
)
